obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)		+= mdnie_lite.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS)	+= lcd_sysfs.o
obj-$(CONFIG_PANEL_S6E3FA2_FHD) += s6e3fa2_fhd_lcd_ctrl.o dimming_core.o dsim_backlight_s6e3fa2.o
obj-$(CONFIG_PANEL_S6E3HF4_WQHD) += s6e3ha3_s6e3ha2_wqhd_lcd_ctrl.o dimming_core_hero.o dsim_backlight_dynamic.o
obj-$(CONFIG_PANEL_S6E3HF4_WQHD_HAECHI) += s6e3hf4_wqhd_haechi_lcd_ctrl.o dimming_core_hero.o dsim_backlight_dynamic.o
obj-$(CONFIG_PANEL_S6E3HA3_DYNAMIC) += s6e3ha3_s6e3ha2_wqhd_lcd_ctrl.o dimming_core.o dsim_backlight_dynamic.o
obj-$(CONFIG_PANEL_S6E3HA5_WQHD) += s6e3hf4_s6e3ha5_wqhd_lcd_ctrl.o dimming_core_hero.o dsim_backlight_grace.o
obj-$(CONFIG_PANEL_S6E3HF2_WQXGA) += s6e3hf2_wqxga_lcd_ctrl.o dimming_core.o dsim_backlight_u.o
obj-$(CONFIG_PANEL_S6E3HF4_WQXGA) += s6e3hf4_wqxga_lcd_ctrl.o dimming_core_hero.o dsim_backlight_u.o
obj-$(CONFIG_PANEL_DDI_SPI) += ddi_spi.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_SUPPORT_POC_FLASH) += poc.o

