# Exynos DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS_DEVFREQ)	+= exynos-devfreq.o
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos_ppmu.o exynos4_bus.o
obj-$(CONFIG_ARM_EXYNOS5_BUS_DEVFREQ)	+= exynos_ppmu.o exynos5_bus.o
obj-$(CONFIG_ARM_EXYNOS8890_BUS_DEVFREQ)+= exynos8890_bus_mif.o exynos8890_bus_int.o exynos8890_bus_disp.o exynos8890_bus_cam.o
