/* linux/drivers/media/video/exynos/fimg2d_v5/fimg2d5x_regs.h
 *
 * Copyright (c) 2015 Samsung Electronics Co., Ltd.
 *	http://www.samsung.com/
 *
 * Register Definitions for Samsung Graphics 2D Hardware
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/

#ifndef __FIMG2D5X_REGS_H
#define __FIMG2D5x_REGS_H __FILE__

/* Macros */
#define FIMG2D_ADDR(v)		((v) << 0)
#define FIMG2D_STRIDE(v)	(((v) & (0x1ffff)) << 0)
#define FIMG2D_OFFSET(v)	(((v) & (0x3fff)) << 0)
#define FIMG2D_SIZE(w, h)	((((h) & 0x1fff) << 16) | (((w) & 0x1fff) << 0))
#define FIMG2D_COLOR(v)		((v) << 0)

/* Actual image width = COMP_IMAGE_WIDWTH + 1'b1
 * Actual image height = COMP_IMAGE_HEIGHT + 1'b1
 * So COMP_XX() macro calculates minus one. */
#define FIMG2D_COMP_WIDTH(v)	((((v) & (0x3fff)) - 1) << 0)
#define FIMG2D_COMP_HEIGHT(v)	((((v) & (0x3fff)) - 1) << 0)

#define FIMG2D_COMP_ALIGN_ADDR		16

#define LAYER_OFFSET(n)		((0x100) * (n))
#define LAYER_SET(n, name)	(LAYER_OFFSET(n) + FIMG2D_LAYER0_##name##_REG)

#define FIMG2D_LAYERn_COMMAND_REG(n)		LAYER_SET(n, COMMAND)
#define FIMG2D_LAYERn_SELECT_REG(n)		LAYER_SET(n, SELECT)
#define FIMG2D_LAYERn_DIRECT_REG(n)		LAYER_SET(n, DIRECT)
#define FIMG2D_LAYERn_DST_LEFT_REG(n)		LAYER_SET(n, DST_LEFT)
#define FIMG2D_LAYERn_DST_TOP_REG(n)		LAYER_SET(n, DST_TOP)
#define FIMG2D_LAYERn_DST_RIGHT_REG(n)		LAYER_SET(n, DST_RIGHT)
#define FIMG2D_LAYERn_DST_BOTTOM_REG(n)		LAYER_SET(n, DST_BOTTOM)
#define FIMG2D_LAYERn_BASE_ADDR_REG(n)		LAYER_SET(n, BASE_ADDR)
#define FIMG2D_LAYERn_STRIDE_REG(n)		LAYER_SET(n, STRIDE)
#define FIMG2D_LAYERn_COLOR_MODE_REG(n)		LAYER_SET(n, COLOR_MODE)
#define FIMG2D_LAYERn_LEFT_REG(n)		LAYER_SET(n, LEFT)
#define FIMG2D_LAYERn_TOP_REG(n)		LAYER_SET(n, TOP)
#define FIMG2D_LAYERn_RIGHT_REG(n)		LAYER_SET(n, RIGHT)
#define FIMG2D_LAYERn_BOTTOM_REG(n)		LAYER_SET(n, BOTTOM)
#define FIMG2D_LAYERn_BLEND_FUNCTION_REG(n)	LAYER_SET(n, BLEND_FUNCTION)
#define FIMG2D_LAYERn_REPEAT_MODE_REG(n)	LAYER_SET(n, REPEAT_MODE)
#define FIMG2D_LAYERn_PAD_VALUE_REG(n)		LAYER_SET(n, PAD_VALUE)
#define FIMG2D_LAYERn_SCALE_CTRL_REG(n)		LAYER_SET(n, SCALE_CTRL)
#define FIMG2D_LAYERn_XSCALE_REG(n)		LAYER_SET(n, XSCALE)
#define FIMG2D_LAYERn_YSCALE_REG(n)		LAYER_SET(n, YSCALE)
#define FIMG2D_LAYERn_X_PHASE_REG(n)		LAYER_SET(n, X_PHASE)
#define FIMG2D_LAYERn_Y_PHASE_REG(n)		LAYER_SET(n, Y_PHASE)
#define FIMG2D_LAYERn_COLOR_REG(n)		LAYER_SET(n, COLOR)
#define FIMG2D_LAYERn_ALPHA_COLOR_REG(n)	LAYER_SET(n, ALPHA_COLOR)
#define FIMG2D_LAYERn_HEADER_BASE_ADDR_REG(n)	LAYER_SET(n, HEADER_BASE_ADDR)
#define FIMG2D_LAYERn_PAYLOAD_BASE_ADDR_REG(n)	LAYER_SET(n, PAYLOAD_BASE_ADDR)
#define FIMG2D_LAYERn_COMP_IMAGE_WIDTH_REG(n)	LAYER_SET(n, COMP_IMAGE_WIDTH)
#define FIMG2D_LAYERn_COMP_IMAGE_HEIGHT_REG(n)	LAYER_SET(n, COMP_IMAGE_HEIGHT)

/* Registers */
/* 1. General Registers */
#define FIMG2D_SOFT_RESET_REG			(0x000)
#define FIMG2D_INTEN_REG			(0x004)
#define FIMG2D_INTC_PEND_REG			(0x00c)
#define FIMG2D_FIFO_STAT_REG			(0x010)
#define FIMG2D_VERSION_INFO_REG			(0x014)
#define FIMG2D_AXI_MODE_REG			(0x01c)
#define FIMG2D_COMP_DEBUG_ADDR_REG		(0x0f0)
#define FIMG2D_COMP_DEBUG_DATA_REG		(0x0f4)

/* 2. G2D command Registers */
#define FIMG2D_BITBLT_START_REG			(0x100)
#define FIMG2D_BITBLT_COMMAND_REG		(0x104)
#define FIMG2D_LAYER_UPDATE_REG			(0x108)

/* 3. Destination Registers */
#define FIMG2D_DST_BASE_ADDR_REG		(0x120)
#define FIMG2D_DST_STRIDE_REG			(0x124)
#define FIMG2D_DST_COLOR_MODE_REG		(0x12c)
#define FIMG2D_DST_LEFT_REG			(0x130)
#define FIMG2D_DST_TOP_REG			(0x134)
#define FIMG2D_DST_RIGHT_REG			(0x138)
#define FIMG2D_DST_BOTTOM_REG			(0x13c)
#define FIMG2D_DST_COLOR_REG			(0x140)
#define FIMG2D_DST_INIT_COLOR_REG		(0x144)

/* 4. Layer0 Registers */
#define FIMG2D_LAYER0_COMMAND_REG		(0x200)
#define FIMG2D_LAYER0_SELECT_REG		(0x204)
#define FIMG2D_LAYER0_DIRECT_REG		(0x208)
#define FIMG2D_LAYER0_DST_LEFT_REG		(0x20c)
#define FIMG2D_LAYER0_DST_TOP_REG		(0x210)
#define FIMG2D_LAYER0_DST_RIGHT_REG		(0x214)
#define FIMG2D_LAYER0_DST_BOTTOM_REG		(0x218)
#define FIMG2D_LAYER0_BASE_ADDR_REG		(0x21c)
#define FIMG2D_LAYER0_STRIDE_REG		(0x220)
#define FIMG2D_LAYER0_COLOR_MODE_REG		(0x228)
#define FIMG2D_LAYER0_LEFT_REG			(0x22c)
#define FIMG2D_LAYER0_TOP_REG			(0x230)
#define FIMG2D_LAYER0_RIGHT_REG			(0x234)
#define FIMG2D_LAYER0_BOTTOM_REG		(0x238)

/* BLEND_FUNCTION doesn't exist for layer 0.
 * It is defined for access by offset. */
#define FIMG2D_LAYER0_BLEND_FUNCTION_REG	(0x23c)

#define FIMG2D_LAYER0_REPEAT_MODE_REG		(0x240)
#define FIMG2D_LAYER0_PAD_VALUE_REG		(0x244)
#define FIMG2D_LAYER0_SCALE_CTRL_REG		(0x248)
#define FIMG2D_LAYER0_XSCALE_REG		(0x24c)
#define FIMG2D_LAYER0_YSCALE_REG		(0x250)
#define FIMG2D_LAYER0_X_PHASE_REG		(0x254)
#define FIMG2D_LAYER0_Y_PHASE_REG		(0x258)
#define FIMG2D_LAYER0_COLOR_REG			(0x25c)
#define FIMG2D_LAYER0_ALPHA_COLOR_REG		(0x260)
#define FIMG2D_LAYER0_HEADER_BASE_ADDR_REG	(0x264)
#define FIMG2D_LAYER0_PAYLOAD_BASE_ADDR_REG	(0x268)
#define FIMG2D_LAYER0_COMP_IMAGE_WIDTH_REG	(0x270)
#define FIMG2D_LAYER0_COMP_IMAGE_HEIGHT_REG	(0x274)

/* 5. Layer1 Registers */
#define FIMG2D_LAYER1_COMMAND_REG		(0x300)
#define FIMG2D_LAYER1_SELECT_REG		(0x304)
#define FIMG2D_LAYER1_DIRECT_REG		(0x308)
#define FIMG2D_LAYER1_DST_LEFT_REG		(0x30c)
#define FIMG2D_LAYER1_DST_TOP_REG		(0x310)
#define FIMG2D_LAYER1_DST_RIGHT_REG		(0x314)
#define FIMG2D_LAYER1_DST_BOTTOM_REG		(0x318)
#define FIMG2D_LAYER1_BASE_ADDR_REG		(0x31c)
#define FIMG2D_LAYER1_STRIDE_REG		(0x320)
#define FIMG2D_LAYER1_COLOR_MODE_REG		(0x328)
#define FIMG2D_LAYER1_LEFT_REG			(0x32c)
#define FIMG2D_LAYER1_TOP_REG			(0x330)
#define FIMG2D_LAYER1_RIGHT_REG			(0x334)
#define FIMG2D_LAYER1_BOTTOM_REG		(0x338)
#define FIMG2D_LAYER1_BLEND_FUNCTION_REG	(0x33c)
#define FIMG2D_LAYER1_REPEAT_MODE_REG		(0x340)
#define FIMG2D_LAYER1_PAD_VALUE_REG		(0x344)
#define FIMG2D_LAYER1_SCALE_CTRL_REG		(0x348)
#define FIMG2D_LAYER1_XSCALE_REG		(0x34c)
#define FIMG2D_LAYER1_YSCALE_REG		(0x350)
#define FIMG2D_LAYER1_X_PHASE_REG		(0x354)
#define FIMG2D_LAYER1_Y_PHASE_REG		(0x358)
#define FIMG2D_LAYER1_COLOR_REG			(0x35c)
#define FIMG2D_LAYER1_ALPHA_COLOR_REG		(0x360)
#define FIMG2D_LAYER1_HEADER_BASE_ADDR_REG	(0x364)
#define FIMG2D_LAYER1_PAYLOAD_BASE_ADDR_REG	(0x368)
#define FIMG2D_LAYER1_COMP_IMAGE_WIDTH_REG	(0x370)
#define FIMG2D_LAYER1_COMP_IMAGE_HEIGHT_REG	(0x374)

/* 6. Layer2 Registers */
#define FIMG2D_LAYER2_COMMAND_REG		(0x400)
#define FIMG2D_LAYER2_SELECT_REG		(0x404)
#define FIMG2D_LAYER2_DIRECT_REG		(0x408)
#define FIMG2D_LAYER2_DST_LEFT_REG		(0x40c)
#define FIMG2D_LAYER2_DST_TOP_REG		(0x410)
#define FIMG2D_LAYER2_DST_RIGHT_REG		(0x414)
#define FIMG2D_LAYER2_DST_BOTTOM_REG		(0x418)
#define FIMG2D_LAYER2_BASE_ADDR_REG		(0x41c)
#define FIMG2D_LAYER2_STRIDE_REG		(0x420)
#define FIMG2D_LAYER2_COLOR_MODE_REG		(0x428)
#define FIMG2D_LAYER2_LEFT_REG			(0x42c)
#define FIMG2D_LAYER2_TOP_REG			(0x430)
#define FIMG2D_LAYER2_RIGHT_REG			(0x434)
#define FIMG2D_LAYER2_BOTTOM_REG		(0x438)
#define FIMG2D_LAYER2_BLEND_FUNCTION_REG	(0x43c)
#define FIMG2D_LAYER2_REPEAT_MODE_REG		(0x440)
#define FIMG2D_LAYER2_PAD_VALUE_REG		(0x444)
#define FIMG2D_LAYER2_SCALE_CTRL_REG		(0x448)
#define FIMG2D_LAYER2_XSCALE_REG		(0x44c)
#define FIMG2D_LAYER2_YSCALE_REG		(0x450)
#define FIMG2D_LAYER2_X_PHASE_REG		(0x454)
#define FIMG2D_LAYER2_Y_PHASE_REG		(0x458)
#define FIMG2D_LAYER2_COLOR_REG			(0x45c)
#define FIMG2D_LAYER2_ALPHA_COLOR_REG		(0x460)
#define FIMG2D_LAYER2_HEADER_BASE_ADDR_REG	(0x464)
#define FIMG2D_LAYER2_PAYLOAD_BASE_ADDR_REG	(0x468)
#define FIMG2D_LAYER2_COMP_IMAGE_WIDTH_REG	(0x470)
#define FIMG2D_LAYER2_COMP_IMAGE_HEIGHT_REG	(0x474)

/* Bit Definitions */

/* FIMG2D_SOFT_RESET_REG */
#define FIMG2D_SFR_CLEAR			(1 << 1)
#define FIMG2D_SOFT_RESET			(1 << 0)

/* FIMG2D_INTEN_REG */
/* TODO: INT TYPE is hidden? */
#define FIMG2D_INT_TYPE_EDGE			(1 << 4)
#define FIMG2D_INT_TYPE_LEVEL			(0 << 4)

#define FIMG2D_BLIT_INT_ENABLE			(1 << 0)

/* FIMG2D_INTC_PEND_REG */
#define FIMG2D_BLIT_INT_FLAG			(1 << 0)

/* FIMG2D_FIFO_STAT_REG */
#define FIMG2D_BLIT_FINISHED			(1 << 0)

/* FIMG2D_VERSION_INFO_REG */
#define FIMG2D_VERSION_MAIN			(0xf << 28)
#define FIMG2D_VERSION_SUB			(0xf << 24)
#define FIMG2D_VERSION_SUBSUB			(0xf << 20)

/* FIMG2D_AXI_MODE_REG */
#define FIMG2D_AXI_AWUSERS_SHIFT		(16)
#define FIMG2D_AXI_ARUSERS_SHIFT		(8)
#define FIMG2D_AXI_AWCACHE_SHIFT		(4)
#define FIMG2D_AXI_ARCACHE_SHIFT		(0)

/* FIMG2D_COMP_DEBUG_ADDR_REG */
#define FIMG2D_COMP_DEBUG_ADDR_MASK		(0xf)
#define FIMG2D_COMP_DEBUG_ADDR_SHIFT		(0)

/* FIMG2D_COMP_DEBUG_DATA_REG */

/* FIMG2D_BITBLT_START_REG */
#define FIMG2D_START_BITBLT			(1 << 0)

/* FIMG2D_BITBLT_COMMAND_REG */
#define FIMG2D_DST_DE_PREMULT			(1 << 29)
#define FIMG2D_ENABLE_DITHER			(1 << 16)

/* FIMG2D_LAYER_UPDATE_REG */
#define FIMG2D_LAYER0_UPDATED			(1 << 0)
#define FIMG2D_LAYER1_UPDATED			(1 << 1)
#define FIMG2D_LAYER2_UPDATED			(1 << 2)

/* FIMG2D_DST_BASE_ADDR_REG */
/* FIMG2D_DST_STRIDE_REG */

/* FIMG2D_DST_COLOR_MODE_REG */
#define FIMG2D_DST_DATA_FORMAT_8888		(0 << 16)
#define FIMG2D_DST_DATA_FORMAT_565		(1 << 16)
#define FIMG2D_DST_DATA_FORMAT_4444		(2 << 16)
#define FIMG2D_DST_DATA_FORMAT_888		(3 << 16)
#define FIMG2D_DST_DATA_FORMAT_1555		(4 << 16)
#define FIMG2D_DST_DATA_FORMAT_5551		(5 << 16)
#define FIMG2D_DST_DATA_FORMAT_8		(6 << 16)

#define FIMG2D_DST_CHANNEL_SEL3_SHIFT		(12)
#define FIMG2D_DST_CHANNEL_SEL2_SHIFT		(8)
#define FIMG2D_DST_CHANNEL_SEL1_SHIFT		(4)
#define FIMG2D_DST_CHANNEL_SEL0_SHIFT		(0)

/* FIMG2D_DST_LEFT_REG */
/* FIMG2D_DST_TOP_REG */
/* FIMG2D_DST_RIGHT_REG */
/* FIMG2D_DST_BOTTOM_REG */

/* FIMG2D_DST_COLOR_REG */
#define FIMG2D_DST_CONSTANT_A_SHIFT		(24)
#define FIMG2D_DST_CONSTANT_R_SHIFT		(16)
#define FIMG2D_DST_CONSTANT_G_SHIFT		(8)
#define FIMG2D_DST_CONSTANT_B_SHIFT		(0)

/* FIMG2D_DST_INIT_COLOR_REG */
#define FIMG2D_DST_INIT_A_SHIFT			(24)
#define FIMG2D_DST_INIT_R_SHIFT			(16)
#define FIMG2D_DST_INIT_G_SHIFT			(8)
#define FIMG2D_DST_INIT_B_SHIFT			(0)

/* FIMG2D_LAYERn_COMMAND_REG */
#define FIMG2D_SRC_PREMULT_SHIFT		(24)

#define FIMG2D_PREMULT_PER_PIXEL_MUL_GALPHA	(0x3 << 24)
#define FIMG2D_PREMULT_PER_PIXEL		(0x1 << 24)
#define FIMG2D_ALPHA_BLEND_MODE			(1 << 20)
#define FIMG2D_LAYER_OPAQUE			(1 << 1)
#define FIMG2D_LAYER_VALID			(1 << 0)

/* FIMG2D_LAYERn_SELECT_REG */
#define FIMG2D_LAYER_SELECT_NORMAL		(0 << 0)
#define FIMG2D_LAYER_SELECT_CONSTANT_COLOR	(1 << 0)

/* FIMG2D_LAYERn_DIRECT_REG */
#define FIMG2D_LAYER_Y_DIR_NEGATIVE		(1 << 5)
#define FIMG2D_LAYER_X_DIR_NEGATIVE		(1 << 4)

/* FIMG2D_LAYERn_DST_LEFT_REG */
/* FIMG2D_LAYERn_DST_TOP_REG */
/* FIMG2D_LAYERn_DST_RIGHT_REG */
/* FIMG2D_LAYERn_DST_BOTTOM_REG */

/* FIMG2D_LAYERn_BASE_ADDR_REG */
/* FIMG2D_LAYERn_STRIDE_REG */

/* FIMG2D_LAYERn_COLOR_MODE_REG */
#define FIMG2D_LAYER_COMP_FORMAT		(1 << 20)

#define FIMG2D_LAYER_DATA_FORMAT_8888		(0 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_565		(1 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_4444		(2 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_888		(3 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_1555		(4 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_5551		(5 << 16)
#define FIMG2D_LAYER_DATA_FORMAT_8		(6 << 16)

#define FIMG2D_LAYER_CHANNEL_SEL_A_SHIFT	(12)
#define FIMG2D_LAYER_CHANNEL_SEL_R_SHIFT	(8)
#define FIMG2D_LAYER_CHANNEL_SEL_G_SHIFT	(4)
#define FIMG2D_LAYER_CHANNEL_SEL_B_SHIFT	(0)

/* FIMG2D_LAYERn_LEFT_REG */
/* FIMG2D_LAYERn_TOP_REG */
/* FIMG2D_LAYERn_RIGHT_REG */
/* FIMG2D_LAYERn_BOTTOM_REG */

/* FIMG2D_LAYERn_BLEND_FUNCTION_REG [n = 1, 2] */
#define FIMG2D_DARKEN				(1 << 21)
#define FIMG2D_LIGHTEN				(1 << 20)
#define FIMG2D_INV_DST_COEFF			(1 << 18)
#define FIMG2D_INV_SRC_COEFF			(1 << 16)

#define FIMG2D_DST_COEFF_DA_SHIFT		(14)
#define FIMG2D_DST_COEFF_SA_SHIFT		(12)
#define FIMG2D_DST_COEFF_SHIFT			(8)
#define FIMG2D_SRC_COEFF_DA_SHIFT		(6)
#define FIMG2D_SRC_COEFF_SA_SHIFT		(4)
#define FIMG2D_SRC_COEFF_SHIFT			(0)

/* FIMG2D_LAYERn_REPEAT_MODE_REG */
#define FIMG2D_LAYER_REPEAT_X_NORMAL		(0 << 0)
#define FIMG2D_LAYER_REPEAT_X_PAD		(1 << 0)
#define FIMG2D_LAYER_REPEAT_X_REFLECT		(2 << 0)
#define FIMG2D_LAYER_REPEAT_X_CLAMP		(3 << 0)
#define FIMG2D_LAYER_REPEAT_X_NONE		(4 << 0)

#define FIMG2D_LAYER_REPEAT_Y_NORMAL		(0 << 4)
#define FIMG2D_LAYER_REPEAT_Y_PAD		(1 << 4)
#define FIMG2D_LAYER_REPEAT_Y_REFLECT		(2 << 4)
#define FIMG2D_LAYER_REPEAT_Y_CLAMP		(3 << 4)
#define FIMG2D_LAYER_REPEAT_Y_NONE		(4 << 4)

#define FIMG2D_LAYER_REPEAT_Y_MASK		(4)

/* FIMG2D_LAYERn_PAD_REG */

/* FIMG2D_LAYERn_SCALE_CTRL_REG */
#define FIMG2D_LAYER_SCALE_MODE_BILINEAR	(2 << 0)

/* FIMG2D_LAYERn_XSCALE_REG */
/* FIMG2D_LAYERn_YSCALE_REG */
/* FIMG2D_LAYERn_X_PHASE_REG */
/* FIMG2D_LAYERn_Y_PHASE_REG */

/* FIMG2D_LAYERn_COLOR_REG */
#define FIMG2D_LAYER_CONSTANT_A_SHIFT		(24)
#define FIMG2D_LAYER_CONSTANT_R_SHIFT		(16)
#define FIMG2D_LAYER_CONSTANT_G_SHIFT		(8)
#define FIMG2D_LAYER_CONSTANT_B_SHIFT		(0)

/* FIMG2D_LAYERn_ALPHA_COLOR_REG */
#define FIMG2D_LAYER_DST_GLOBAL_R		(24)
#define FIMG2D_LAYER_DST_GLOBAL_G		(16)
#define FIMG2D_LAYER_DST_GLOBAL_B		(8)
#define FIMG2D_LAYER_DST_GLOBAL_A		(0)

/* FIMG2D_LAYERn_HEADER_BASE_ADDR_REG */
/* FIMG2D_LAYERn_PAYLOAD_BASE_ADDR_REG */
/* FIMG2D_LAYERn_COMP_IMAGE_WIDTH_REG */
/* FIMG2D_LAYERn_COMP_IMAGE_HEIGHT_REG */
#endif /* __FIMG2D5X_REGS_H */
