#
# Makefile for radios with Richwave RTC6213N FM Tuner
#

radio-usb-rtc6213n-objs	:= radio-rtc6213n-usb.o radio-rtc6213n-common.o
radio-i2c-rtc6213n-objs	:= radio-rtc6213n-i2c.o radio-rtc6213n-common.o

obj-$(CONFIG_USB_RTC6213N) += radio-usb-rtc6213n.o
obj-$(CONFIG_I2C_RTC6213N) += radio-i2c-rtc6213n.o
