#
# Makefile for gps devices
#

obj-$(CONFIG_GPS_BCM4752)		+= sec_gps_bcm4752.o
obj-$(CONFIG_GPS_BCM47521)		+= sec_gps_bcm47521.o
obj-$(CONFIG_GPS_BCM4753)		+= sec_gps_bcm4753.o
obj-$(CONFIG_GPS_BCM47531)		+= sec_gps_bcm47531.o

