obj-$(CONFIG_VIDEO_EXYNOS_MFC) := s5p-mfc.o
s5p-mfc-y += s5p_mfc.o s5p_mfc_intr.o
s5p-mfc-y += s5p_mfc_dec.o s5p_mfc_enc.o
s5p-mfc-y += s5p_mfc_ctrl.o s5p_mfc_inst.o
s5p-mfc-y += s5p_mfc_mem.o s5p_mfc_pm.o s5p_mfc_qos.o
s5p-mfc-y += s5p_mfc_buf.o s5p_mfc_enc_param.o s5p_mfc_utils.o
s5p-mfc-y += s5p_mfc_nal_q.o
obj-$(CONFIG_EXYNOS_MFC_V10) += s5p_mfc_opr_v6.o s5p_mfc_cmd_v6.o
