obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o oled_backlight.o
obj-$(CONFIG_PANEL_AID_DIMMING) += smart_dimming_core.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)		+= mdnie_lite.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS)	+= lcd_sysfs.o
obj-$(CONFIG_PANEL_S6E3HF2_WQXGA) += s6e3hf2_wqxga_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E36W0X10) += s6e36w0x10_lcd_ctrl.o
