#
# Makefile for ccic devices
#

obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o
obj-$(CONFIG_CCIC_ALTERNATE_MODE)	+= ccic_alternate.o ccic_misc.o
obj-$(CONFIG_CCIC_S2MM003)		+= s2mm003.o
obj-$(CONFIG_CCIC_S2MM005)		+= s2mm005_fw.o s2mm005_cc.o s2mm005_pd.o s2mm005.o