obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o oled_backlight.o
obj-$(CONFIG_PANEL_AID_DIMMING) += smart_dimming_core.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)		+= mdnie_lite.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS)	+= lcd_sysfs.o
obj-$(CONFIG_PANEL_S6E3FA3_FHD) += s6e3fa3_fhd_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3HF4_FHD) += s6e3hf4_fhd_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3HF3_FHD) += s6e3hf3_fhd_lcd_ctrl.o
