/* linux/drivers/video/exynos_decon/panel/s6e3fa3_aid_baic_info.h
 *
 * Header file for Samsung AID Dimming Driver.
 *
 * Copyright (c) 2013 Samsung Electronics
 * Minwoo Kim <minwoo7945.kim@samsung.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/


/* CAUTION !!!
This file was generated by Smart Dimming Header Generation Tool. Do not modify manually */

#ifndef __S6E3FA3_AID_BASIC_INFO__
#define __S6E3FA3_AID_BASIC_INFO__

#define VT_INDEX			0
#define MAX_BRIGHTNESS			420
#define MULTIPLE_VREGOUT			6144
#define MULTIPLY_VALUE			1024
#define MAX_GRAYSCALE 			256

enum {
	CI_RED = 0,
	CI_GREEN,
	CI_BLUE,
	CI_MAX,
};


#define GAMMA_COMMAND			0xca
#define AOR_COMMAND			0xb2
#define AOR_COMMAND_CNT			3
#define GAMMA_COMMAND_CNT			36

#define VREF_POINT_CNT			10

#define VREF_CALC_METHOD_DIRECT 0
#define VREF_CALC_METHOD_INDIRECT 1
#define VREF_CALC_METHOD_FIX 2
#define VREF_CALC_METHOD_CNT 3

#define VREF_CAL_REF_VREG 0
#define VREF_CAL_REF_VT 1

#define MAX_DIMMING_INFO_COUNT 			75

struct aid_dimming_info {
	unsigned int phy_br;
	unsigned int ref_br;
	unsigned int aor;
	const unsigned int *ref_gma;
	const unsigned char mps;
	const unsigned char elv;
	const char* elvss_offset;
};

struct gamma_formula {
	int num0;
	int num1;
	int deno;
};


#endif
