
obj-$(CONFIG_INPUT_WACOM)	+= wacom_i2c.o wacom_i2c_firm.o wacom_i2c_func.o

obj-$(CONFIG_EPEN_WACOM_G5SP)	+= wacom_i2c_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PM)	+= wacom_i2c_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PL)	+= w9002_flash.o
obj-$(CONFIG_EPEN_WACOM_G9PLL)	+= w9002_flash.o
obj-$(CONFIG_EPEN_WACOM_G10PM)	+= w9002_flash.o
obj-$(CONFIG_EPEN_WACOM_W9012)	+= w9012_flash.o
obj-$(CONFIG_EPEN_WACOM_W9014)	+= w9014_flash.o
obj-$(CONFIG_EPEN_WACOM_W9018)	+= w9018_flash.o
